CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tg_id text NOT NULL,
	is_admin bool NOT NULL DEFAULT false,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_un UNIQUE (tg_id)
);

CREATE TABLE public.users_states (
	user_id int4 NOT NULL,
	state text NOT NULL,
	data text NULL,
	CONSTRAINT users_states_un UNIQUE (user_id),
	CONSTRAINT users_states_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.gives (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"owner" int4 NOT NULL,
	is_active bool NOT NULL DEFAULT false,
	title text NULL,
	description text NULL,
	images _text NULL,
	start_at timestamptz NULL,
	finish_at timestamptz NULL,
	channel int NULL,
	target_channels _int8 NULL,
	CONSTRAINT gives_pk PRIMARY KEY (id),
	CONSTRAINT gives_fk FOREIGN KEY ("owner") REFERENCES public.users(id)
);